version: 2
before:
  hooks:
    - go mod tidy

builds:
  # Exporter build
  - main: cmd/gitlab-ci-exporter/main.go
    binary: gitlab-ci-exporter
    id: gitlab-ci-exporter

    env:
      - CGO_ENABLED=0

    goos:
      - "windows"
      - "linux"
      - "darwin"
    goarch:
      - "amd64"
      - "386"
      - "arm"
      - "arm64"
    ignore:
      - goos: "darwin"
        goarch: "386"
      - goos: "windows"
        goarch: "arm"
      - goos: "windows"
        goarch: "arm64"

archives:
  - formats: [ zip ]
    id: gitlab-ci-exporter
    builds: [ gitlab-ci-exporter ]
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}

checksum:
  algorithm: sha256
