// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: pkg/monitor/protobuf/monitor.proto

package protobuf

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_pkg_monitor_protobuf_monitor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_monitor_protobuf_monitor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_pkg_monitor_protobuf_monitor_proto_rawDescGZIP(), []int{0}
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_pkg_monitor_protobuf_monitor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_monitor_protobuf_monitor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_pkg_monitor_protobuf_monitor_proto_rawDescGZIP(), []int{1}
}

func (x *Config) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type Telemetry struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	GitlabApiUsage          float64                `protobuf:"fixed64,1,opt,name=gitlab_api_usage,json=gitlabApiUsage,proto3" json:"gitlab_api_usage,omitempty"`
	GitlabApiRequestsCount  uint64                 `protobuf:"varint,2,opt,name=gitlab_api_requests_count,json=gitlabApiRequestsCount,proto3" json:"gitlab_api_requests_count,omitempty"`
	GitlabApiRateLimit      float64                `protobuf:"fixed64,3,opt,name=gitlab_api_rate_limit,json=gitlabApiRateLimit,proto3" json:"gitlab_api_rate_limit,omitempty"`
	GitlabApiLimitRemaining uint64                 `protobuf:"varint,4,opt,name=gitlab_api_limit_remaining,json=gitlabApiLimitRemaining,proto3" json:"gitlab_api_limit_remaining,omitempty"`
	TasksBufferUsage        float64                `protobuf:"fixed64,5,opt,name=tasks_buffer_usage,json=tasksBufferUsage,proto3" json:"tasks_buffer_usage,omitempty"`
	TasksExecutedCount      uint64  `protobuf:"varint,6,opt,name=tasks_executed_count,json=tasksExecutedCount,proto3" json:"tasks_executed_count,omitempty"`
	Projects                *Entity `protobuf:"bytes,7,opt,name=projects,proto3" json:"projects,omitempty"`
	Refs                    *Entity `protobuf:"bytes,8,opt,name=refs,proto3" json:"refs,omitempty"`
	Envs                    *Entity `protobuf:"bytes,9,opt,name=envs,proto3" json:"envs,omitempty"`
	Runners                 *Entity `protobuf:"bytes,10,opt,name=runners,proto3" json:"runners,omitempty"`
	Metrics                 *Entity `protobuf:"bytes,11,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Telemetry) Reset() {
	*x = Telemetry{}
	mi := &file_pkg_monitor_protobuf_monitor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telemetry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telemetry) ProtoMessage() {}

func (x *Telemetry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_monitor_protobuf_monitor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telemetry.ProtoReflect.Descriptor instead.
func (*Telemetry) Descriptor() ([]byte, []int) {
	return file_pkg_monitor_protobuf_monitor_proto_rawDescGZIP(), []int{2}
}

func (x *Telemetry) GetGitlabApiUsage() float64 {
	if x != nil {
		return x.GitlabApiUsage
	}
	return 0
}

func (x *Telemetry) GetGitlabApiRequestsCount() uint64 {
	if x != nil {
		return x.GitlabApiRequestsCount
	}
	return 0
}

func (x *Telemetry) GetGitlabApiRateLimit() float64 {
	if x != nil {
		return x.GitlabApiRateLimit
	}
	return 0
}

func (x *Telemetry) GetGitlabApiLimitRemaining() uint64 {
	if x != nil {
		return x.GitlabApiLimitRemaining
	}
	return 0
}

func (x *Telemetry) GetTasksBufferUsage() float64 {
	if x != nil {
		return x.TasksBufferUsage
	}
	return 0
}

func (x *Telemetry) GetTasksExecutedCount() uint64 {
	if x != nil {
		return x.TasksExecutedCount
	}
	return 0
}

func (x *Telemetry) GetProjects() *Entity {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *Telemetry) GetRefs() *Entity {
	if x != nil {
		return x.Refs
	}
	return nil
}

func (x *Telemetry) GetEnvs() *Entity {
	if x != nil {
		return x.Envs
	}
	return nil
}

func (x *Telemetry) GetRunners() *Entity {
	if x != nil {
		return x.Runners
	}
	return nil
}

func (x *Telemetry) GetMetrics() *Entity {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	LastGc        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_gc,json=lastGc,proto3" json:"last_gc,omitempty"`
	LastPull      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_pull,json=lastPull,proto3" json:"last_pull,omitempty"`
	NextGc        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=next_gc,json=nextGc,proto3" json:"next_gc,omitempty"`
	NextPull      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=next_pull,json=nextPull,proto3" json:"next_pull,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_pkg_monitor_protobuf_monitor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_monitor_protobuf_monitor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_pkg_monitor_protobuf_monitor_proto_rawDescGZIP(), []int{3}
}

func (x *Entity) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Entity) GetLastGc() *timestamppb.Timestamp {
	if x != nil {
		return x.LastGc
	}
	return nil
}

func (x *Entity) GetLastPull() *timestamppb.Timestamp {
	if x != nil {
		return x.LastPull
	}
	return nil
}

func (x *Entity) GetNextGc() *timestamppb.Timestamp {
	if x != nil {
		return x.NextGc
	}
	return nil
}

func (x *Entity) GetNextPull() *timestamppb.Timestamp {
	if x != nil {
		return x.NextPull
	}
	return nil
}

var File_pkg_monitor_protobuf_monitor_proto protoreflect.FileDescriptor

const file_pkg_monitor_protobuf_monitor_proto_rawDesc = "" +
	"\n" +
	"\"pkg/monitor/protobuf/monitor.proto\x12\amonitor\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"\"\n" +
	"\x06Config\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"\x8d\x04\n" +
	"\tTelemetry\x12(\n" +
	"\x10gitlab_api_usage\x18\x01 \x01(\x01R\x0egitlabApiUsage\x129\n" +
	"\x19gitlab_api_requests_count\x18\x02 \x01(\x04R\x16gitlabApiRequestsCount\x121\n" +
	"\x15gitlab_api_rate_limit\x18\x03 \x01(\x01R\x12gitlabApiRateLimit\x12;\n" +
	"\x1agitlab_api_limit_remaining\x18\x04 \x01(\x04R\x17gitlabApiLimitRemaining\x12,\n" +
	"\x12tasks_buffer_usage\x18\x05 \x01(\x01R\x10tasksBufferUsage\x120\n" +
	"\x14tasks_executed_count\x18\x06 \x01(\x04R\x12tasksExecutedCount\x12+\n" +
	"\bprojects\x18\a \x01(\v2\x0f.monitor.EntityR\bprojects\x12#\n" +
	"\x04refs\x18\b \x01(\v2\x0f.monitor.EntityR\x04refs\x12#\n" +
	"\x04envs\x18\t \x01(\v2\x0f.monitor.EntityR\x04envs\x12)\n" +
	"\arunners\x18\n" +
	" \x01(\v2\x0f.monitor.EntityR\arunners\x12)\n" +
	"\ametrics\x18\v \x01(\v2\x0f.monitor.EntityR\ametrics\"\xfa\x01\n" +
	"\x06Entity\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\x123\n" +
	"\alast_gc\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06lastGc\x127\n" +
	"\tlast_pull\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\blastPull\x123\n" +
	"\anext_gc\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06nextGc\x127\n" +
	"\tnext_pull\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bnextPull2q\n" +
	"\aMonitor\x12.\n" +
	"\tGetConfig\x12\x0e.monitor.Empty\x1a\x0f.monitor.Config\"\x00\x126\n" +
	"\fGetTelemetry\x12\x0e.monitor.Empty\x1a\x12.monitor.Telemetry\"\x000\x01B?Z=github.com/helvethink/gitlab-ci-exporter/pkg/monitor/protobufb\x06proto3"

var (
	file_pkg_monitor_protobuf_monitor_proto_rawDescOnce sync.Once
	file_pkg_monitor_protobuf_monitor_proto_rawDescData []byte
)

func file_pkg_monitor_protobuf_monitor_proto_rawDescGZIP() []byte {
	file_pkg_monitor_protobuf_monitor_proto_rawDescOnce.Do(func() {
		file_pkg_monitor_protobuf_monitor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_monitor_protobuf_monitor_proto_rawDesc), len(file_pkg_monitor_protobuf_monitor_proto_rawDesc)))
	})
	return file_pkg_monitor_protobuf_monitor_proto_rawDescData
}

var file_pkg_monitor_protobuf_monitor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_monitor_protobuf_monitor_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: monitor.Empty
	(*Config)(nil),                // 1: monitor.Config
	(*Telemetry)(nil),             // 2: monitor.Telemetry
	(*Entity)(nil),                // 3: monitor.Entity
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_pkg_monitor_protobuf_monitor_proto_depIdxs = []int32{
	3,  // 0: monitor.Telemetry.projects:type_name -> monitor.Entity
	3,  // 1: monitor.Telemetry.refs:type_name -> monitor.Entity
	3,  // 2: monitor.Telemetry.envs:type_name -> monitor.Entity
	3,  // 3: monitor.Telemetry.runners:type_name -> monitor.Entity
	3,  // 4: monitor.Telemetry.metrics:type_name -> monitor.Entity
	4,  // 5: monitor.Entity.last_gc:type_name -> google.protobuf.Timestamp
	4,  // 6: monitor.Entity.last_pull:type_name -> google.protobuf.Timestamp
	4,  // 7: monitor.Entity.next_gc:type_name -> google.protobuf.Timestamp
	4,  // 8: monitor.Entity.next_pull:type_name -> google.protobuf.Timestamp
	0,  // 9: monitor.Monitor.GetConfig:input_type -> monitor.Empty
	0,  // 10: monitor.Monitor.GetTelemetry:input_type -> monitor.Empty
	1,  // 11: monitor.Monitor.GetConfig:output_type -> monitor.Config
	2,  // 12: monitor.Monitor.GetTelemetry:output_type -> monitor.Telemetry
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_pkg_monitor_protobuf_monitor_proto_init() }
func file_pkg_monitor_protobuf_monitor_proto_init() {
	if File_pkg_monitor_protobuf_monitor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_monitor_protobuf_monitor_proto_rawDesc), len(file_pkg_monitor_protobuf_monitor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_monitor_protobuf_monitor_proto_goTypes,
		DependencyIndexes: file_pkg_monitor_protobuf_monitor_proto_depIdxs,
		MessageInfos:      file_pkg_monitor_protobuf_monitor_proto_msgTypes,
	}.Build()
	File_pkg_monitor_protobuf_monitor_proto = out.File
	file_pkg_monitor_protobuf_monitor_proto_goTypes = nil
	file_pkg_monitor_protobuf_monitor_proto_depIdxs = nil
}
