{
 "title": "Gitlab Exporter Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DataSource" }
  ]
 },
 "panels": [
  {
   "title": "Nb Projects",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gcpe_projects_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Metrics Count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gcpe_metrics_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ref count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gcpe_refs_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Runners Count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gcpe_runners_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Environment Count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gcpe_environments_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API Request VS API Request Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    { "expr": "gcpe_gitlab_api_requests_count" },
    { "expr": "gcpe_gitlab_api_requests_limit" },
    {
     "expr": "gcpe_gitlab_api_requests_remaining"
    }
   ]
  },
  {
   "title": "Currently queued tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "gcpe_currently_queued_tasks_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scrape duration time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Scrape Series added",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    { "expr": "scrape_series_added", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Runner List",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    { "expr": "gitlab_ci_runners" }
   ]
  }
 ]
}